### ISSUE TITLE
Bag resizing background-size contain sometimes the bag does not take whole height of the div...no good for letter sizing...will find a solution

### ISSUE THREAD

**Issue by DavidLichy** [BurgersOnBrioche/ShopFramework#20]

**Comment by neilsarkar** [comment]
so I think if we do this instead of using a background image, it will always take up full height:

```html
<div style="width: 100%; padding-bottom: 150%; ">
  <img style="width: 100%; " />
</div>
```

that's assuming that the width:height aspect ratio is 1:1.5, adjust accordingly for actual aspect ratio of image
